### ISSUE TITLE
How can use in game?

### ISSUE THREAD

**Issue by Yezzy808** [thebigsmileXD/UserManager#2]
And this plugin cant see in /pl list why?

**Comment by inxomnyaa** [comment]
In game: no idea, i have no psychic powers to remotely read your code

/pl -> Make sure it is enabled, that you use the .phar from poggit and sqlite is properly working

**Comment by Yezzy808** [comment]
> In game: no idea, i have no psychic powers to remotely read your code
> 
> /pl -> Make sure it is enabled, that you use the .phar from poggit and sqlite is properly working

Me:
How to GET Password and enter in config.yml?
